### ISSUE TITLE
Require issues

### ISSUE THREAD

**Issue by sunsheeppoplar** [olalonde/node-yelp#12]
Hi,

I'm not sure if this is a massive error on my end, but I can't get the starter code to get going.

```js
var yelp = new Yelp({
           ^
TypeError: object is not a function
    at Object.<anonymous> (/home/sunsheeppoplar/test/server.js:3:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
```

I've installed the npm and am requiring it in what looks like the same way as your documentation.

```js
var Yelp = require('yelp')

var yelp = new Yelp({
// etc etc 
)}
```

**Comment by olalonde** [comment]
Oops, fixed in 1.0.1. This was due to http://stackoverflow.com/questions/33505992/babel-6-changes-how-it-exports-default/33506169
